// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://lugixaaofxztwovklzxb.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1Z2l4YWFvZnh6dHdvdmtsenhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMyNjMyMzgsImV4cCI6MjA0ODgzOTIzOH0.91FsgC-lmTgdAp745JXdPg3HnRndik9rfXHXGhPHx3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);